### ISSUE TITLE
Input weights shape

### ISSUE THREAD

**Issue by NorhenAbdennadher** [FilippoMB/Reservoir-Computing-framework-for-multivariate-time-series-classification#7]
I'm facing a problem understanding the architecture of the reservoir if we look at it as a neural network. In here the shape of the input for the reservoir "current_input" in the code is (N, V), and the shape of the _input_weights is (internal_units, V).
And normally, the shape of the _input_weights should be (size of reservoir* size of the input).
Can I kindly ask why the size of the _input_weights is (internal_units, V) and not  (internal_units, V*N)?

**Comment by FilippoMB** [comment]
I'm not sure if I understand your problem.
'V' is the size of the input, i.e., the number of input variables.
'internal_units' denotes the size of the reservoir, i.e., the number of output variables.
Therefore, the weights must have shape (V, internal_units), as they map the input from a space of dimensionality 'V' to a space of dimensionality 'internal_units'.

'N' is the number of samples. In reservoir computing (and generally in neural nets) the weights depend on the dimensionality of the samples, not on the number of samples.

**Comment by NorhenAbdennadher** [comment]
Thank you for your answer,
I think in this case, I'm finding troubles understanding the difference
between N, T and V in the MTS.
I'll be grateful if you can provide me explanation about the difference
between T and V especially.

**Comment by FilippoMB** [comment]
- N is the number of the time series in the dataset.
- T is the length of the time series, i.e., the number of time steps.
- V is the number of variables, i.e., how many quantities are measured at each time step. For example, if the time series describes a trajectory of an object in a 3D space, V=3 because you are measuring 3 coordinates at each time step. If the time series is univariate, then V=1.

You can read more about multivariate time series online. There are many tutorials and explanations.

**Comment by NorhenAbdennadher** [comment]
Sorry for asking too many questions, but the 'current_input' in the reservoir.py is of shape (N, V) and you said that 'V' is the size of the input. So the current_input isn't the input for the neural network? So what is exactly the input for the network?
